apiVersion: v1
kind: Namespace
metadata:
  name: hackathon-api2
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: hackathon-api2-user
#   namespace: hackathon-api2
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-api2-deployment
  namespace: hackathon-api2
  labels:
    app: hackathon-api2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-api2
  template:
    metadata:
      labels:
        app: hackathon-api2
    spec:
      serviceAccountName: hackathon-api2-user
      containers:
        - name: hackathon-api2
          image: cagip/hackathon-api:latest
          imagePullPolicy: Always
          env:
            - name: MONGOURI
              value: 'mongodb://mongo:27017/donation?retryWrites=true&w=majority'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi

              
---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-api2-svc
  namespace: hackathon-api2
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: hackathon-api2
  spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hackathon-api2